version: '2.1'

services:
  front:
    build: front/.
    ports:
      - "4444:80"
    depends_on:
      back:
        condition: service_healthy
    links:
      - back

  back:
    build: back/.
    ports:
      - "5000:5000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/persons" ]
      interval: 30s
      timeout: 10s
      retries: 5
